config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations'}
  
  resources :posts do
    get 'delete'
  end
  resources :friendships

  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true
  
  scope :friends, ->(user) { where(user: user.friends) }
end

app/models/user.rb
class User < ApplicationRecord
  require 'securerandom'
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  
  has_many :posts, dependent: :destroy
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user
  
  validates :first_name, :last_name, :login, presence: true

  scope :unfriended, ->(user) do
    joins('LEFT JOIN friendships ON friendships.friend_id = users.id')
      .where('friendships.id is NULL OR friendships.friend_id NOT IN (?)',
             user.friends.ids.present? ? user.friends.ids : 0)
      .where.not(id: user.id)
  end

  def full_name
    "#{first_name} #{last_name}"
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.name.split(' ').first
      user.last_name = auth.info.name.split(' ').last
      user.login = SecureRandom.hex(8)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    user_attributes = %i[
      email password password_confirmation
      login first_name last_name
    ]
    devise_parameter_sanitizer.permit(
      :sign_up, keys: user_attributes
    )
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[login password])
    devise_parameter_sanitizer.permit(
      :account_update, keys: %i[first_name last_name]
    )
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friends = current_user.friends
    @users = User.unfriended(current_user)
  end
  
  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
    if @friendship.save
      redirect_to friendships_path, notice: 'Друг добавлен'
    else
      redirect_to friendships_path, notice: 'Невозможно добавить друга'
    end
  end
  
  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    redirect_to friendships_path, notice: 'Друг удален'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :fetch_posts
  before_action :authenticate_user!
  
  def index
    if params[:query] == 'friends'
      @posts = Post.friends(current_user).order(created_at: :desc)
    elsif params[:query] == 'mine'
      @posts = current_user.posts.order(created_at: :desc)
    else
      @posts = Post.all.order(created_at: :desc)
    end
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.create(post_params)
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
  end
  
  private
  
  def fetch_posts
    @posts = Post.all
  end
  
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/friendships/index.html.slim
.container
  h2 Ваши друзья
  br
  - if current_user.friendships.present?
    table.table
      thead
        tr
          th Полное имя
          th
      tbody
        - current_user.friendships.each do |friendship|
          tr
            td = friendship.friend.full_name
            td = link_to "Удалить из друзей", friendship, method: :delete
  - else
    h4 У вас нет друзей
  hr

  h2 Остальные пользователи
  - if @users.present?
    table.table
      thead
        tr
          th Полное имя
          th
      tbody
        - @users.each do |user|
          tr
            td = user.full_name
            td = link_to 'Добавить в друзья', friendships_path(friend_id: user), :method => :post

app/views/layouts/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#"  TeleportTwitter
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to 'Главная', '/'
        li
          = link_to 'Друзья', friendships_path, class: 'nav-link'

      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li
            = link_to 'Написать комментарий', new_post_path, remote: true, class: 'nav-link'
          li
            = link_to 'Изменить профиль', edit_user_registration_path, class: 'nav-link'
          li
            = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          = link_to 'Войти', new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title TeleportTwitter
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render partial: 'layouts/header'
    = yield
    #post-modal.modal.fade

app/views/layouts/modal.html.slim
#mainModal.modal tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true"
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal"
          span aria-hidden="true" &times;
          span.sr-only Close
        h4#mainModalLabel.modal-title
          = yield :title if content_for? :title
          |&nbsp;

      = yield

app/views/posts/_delete.html.slim
.modal-dialog
  .modal-content
  .modal-header
    h3 Удалить комментарий
  .modal-body
    ul.errors
  .modal-footer
    = link_to 'Да', product_path(@post), method: :delete, remote: true, class: "btn btn-danger" %>
    = link_to 'Нет', "#", class: "btn btn-default", data: { dismiss: "modal" } %>

app/views/posts/_edit.html.slim
.modal-dialog
  .modal-content
    .modal-header
      h3 Редактировать комментарий

    = render 'form'

app/views/posts/_form.html.slim
= simple_form_for(@post, remote: true) do |f|
  .modal-body
    = f.input :content, label: false, placeholder: 'Текст комментария'
  .modal-footer
    = f.button :submit, 'Подтвердить' , class: 'btn btn-success'
    = link_to 'Отменить', '#', class: 'btn', data: {dismiss: 'modal'}

app/views/posts/_index.html.slim
- @posts.each do |post|
  tr
    td = post.user.full_name
    td = post.content
    td = post.created_at.strftime('%d/%m/%y %H:%M')
    td
      - if post.user == current_user
        = link_to 'Изменить', edit_post_path(post), remote: true, class: 'btn btn-info'
        =< link_to 'Удалить', post_path(post), method: :delete, remote: true, class: 'btn btn-danger'

app/views/posts/_new.html.slim
.modal-dialog
  .modal-content
    .modal-header
      h3 Новый комментарий

    = render 'form'

app/views/posts/_save.js.erb
$("ul.errors").html("")
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".post-index").html("<%= escape_javascript(render 'index') %>")
  $("#post-modal").modal("hide")
<% end %>

app/views/posts/create.js.erb
<%= render "save" %>

app/views/posts/delete.js.erb
$("#post-modal").html("<%= escape_javascript(render 'delete') %>")
$("#post-modal").modal("show")

app/views/posts/destroy.js.erb
<%= render "save" %>

app/views/posts/edit.js.erb
$("#post-modal").html("<%= escape_javascript(render 'edit') %>")
$("#post-modal").modal("show")

app/views/posts/index.html.slim
.container
  h2 Комментарии
  = link_to 'Все комментарии', posts_path, class: 'btn btn-success'
  =< link_to 'Комментарии друзей', posts_path(query: 'friends'), class: 'btn btn-success'
  =< link_to 'Мои комментарии', posts_path(query: 'mine'), class: 'btn btn-success'
  table.table
    thead
      tr
        th Автор
        th Комментарий
        th Время создания
        th
    tbody.post-index
      = render 'index'

app/views/posts/new.js.erb
$("#post-modal").html("<%= escape_javascript(render 'new') %>")
$("#post-modal").modal("show")

app/views/posts/update.js.erb
<%= render "save" %>